# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs

cosmo_params:
    omega_b: 0.022301 
    omega_cdm: 0.119444
    H0: 67.74
    tau_reio: 0.0561
    ln10^{10}A_s: 3.047
    n_s: 0.9665
    k_pivot: 0.05
    N_ncdm: 0
    N_ur: 3.046
    #m_ncdm: 0.0

common_params:
    delta__for__galaxies: 200c
    delta__for__matter__density: 200c
    delta__for__electron__density: 200c
    mass__function: T08M200c
    concentration__parameter: B13
    z_min: 0.0
    z_max: 3.0
    M_min: 1.0e10
    M_max: 3.5e15
    redshift_epsabs: 1.0e-40
    redshift_epsrel: 0.0005
    mass_epsabs: 1.0e-40
    mass_epsrel: 0.0005
    ell_max: 1600.0
    ell_min: 2.0
    dell: 10
    non_linear: halofit
    pk_nonlinear_for_vrms2: 1
    hm_consistency: 1
    f_free: 1.0
    x_out_truncated_nfw_profile: 1.
    use_xout_in_density_profile_from_enclosed_mass: 1
    x_out_truncated_density_profile__(electrons): 1. 
    normalize_gas_density_profile: 0
    x_outSZ: 4.
    truncate_wrt_rvir: 0

# parameters that indicate where the observed data that you would like to fit live
data_params:
    data_dir: /global/cscratch1/sd/boryanah/SZ_TNG/
    field_dir: /global/cscratch1/sd/boryanah/SZ_TNG/
    snaps_fn: /global/cscratch1/sd/boryanah/SZ_TNG/snaps_illustris_mtng.txt
    sim_name: MTNG
    fn_base: prof_sph_r200c_m200c_1e12Msun
    sz_base: SZ_sph_cyl_r200c_m200c_1e12Msun
#    dm_base: prof_dm_dm_sph_r200c_m200c_1e12Msun
    dm_base: prof_dm_fp_sph_r200c_m200c_1e12Msun
    snapshots: [179, 214, 237, 264]
    profs_type: ['P_e'] #n_e rho
    logmmin: 12.0 
    logmmax: 15.0 
    nbin_m: 15
    nbin_sec: 1 
    secondary_type: 'conc'
    r_min: 0.03
    r_max: 2.
    
# Parameters to be fitted in MCMC
# [mapping_index, mean, min, max, std, prof_type]
fit_params:
    # standard parameters (pressure)
    A_P0: [0, 1.1, 0., 30., 0.3, 'P_e']
    A_beta: [1, 4.35, 0., 10., 0.1, 'P_e']
    A_xc: [2, 0.497, 0, 3., 0.01, 'P_e']
    alpha_m_P0: [3, 0.154, -5, 5., 0.1, 'P_e']
    alpha_m_xc: [4, -0.00865, -5., 5., 0.1, 'P_e']
    alpha_m_beta: [5, 0.0393, -5., 5., 0.1, 'P_e']
    alpha_z_P0: [6, -0.758, -5., 5., 0.1, 'P_e']
    alpha_z_xc: [7, 0.731, -5., 5., 0.1, 'P_e']
    alpha_z_beta: [8, 0.415, -5., 5., 0.1, 'P_e']
    #alpha: 1
    #gamma: -0.3
    
    # power-law break (pressure)
    alphap_m_P0: [9, 0.154, -3., 3., 0.1, 'P_e']
    alphap_m_xc: [10, -0.00865, -3., 3., 0.1, 'P_e']
    alphap_m_beta: [11, 0.0393, -3., 3., 0.1, 'P_e']
    Mcut_break: [12, 13.8, 12.5, 14.5, 0.05, 'P_e'] # same though

    # concentration dependence (pressure)
#    alpha_c_P0: [13, 0., -3., 3., 0.1, 'P_e']
#    alpha_c_xc: [14, 0., -3., 3., 0.1, 'P_e']
#    alpha_c_beta: [15, 0., -3., 3., 0.1, 'P_e']

    # two-halo fudge factor (pressure)
#    A2h0: [16, 1., 0.5, 10., 0.1, 'P_e']
#    alpha_z_A2h: [14, 0., -3., 3., 0.1, 'n_e']
#    alpha_m_A2h: [15, 0., -3., 3., 0.1, 'n_e']
#    alpha_c_A2h: [19, 0., -3., 3., 0.1, 'n_e']

    alpha: [13, 1., -3., 3., 0.1, 'P_e']
    gamma: [14, -0.3, -3., 3., 0.1, 'P_e']

other_params:
    A_rho0: 1070.949015881 # 797.0901628501481
    A_alpha: 1.4872029221294334 # 1.6561439042009305
    A_beta: 2.12252820935945 # 3.0480895045263368
    alpha_m_rho0: 0.5351783603772226 # 0.6224910287390192
    alpha_m_alpha: -0.07222259808412405 # -0.06318761824171598
    alpha_m_beta: 0.22894920226700674 #0.22929021320998735
    alpha_z_rho0: 0.6692710893936122 # 0.5997950721116475
    alpha_z_alpha: -0.09243465354164133 #-0.09631314417799976
    alpha_z_beta: 0.29722726573399005 # 0.2055953513744834

unused_params:
    # standard parameters (density)
    A_rho0: [0, 4.e3, 1.e2, 1.e4, 10., 'n_e']
    A_alpha: [1, 0.88, 0., 5., 0.1, 'n_e']
    A_beta: [2, 3.83, 0., 5., 0.1, 'n_e']
    alpha_m_rho0: [3, 0.29, -3., 3., 0.1, 'n_e']
    alpha_m_alpha: [4, -0.03, -3., 3., 0.1, 'n_e']
    alpha_m_beta: [5, 0.04, -3., 3., 0.1, 'n_e']
    alpha_z_rho0: [6, -0.66, -3., 3., 0.1, 'n_e']
    alpha_z_alpha: [7, 0.19, -3., 3., 0.1, 'n_e']
    alpha_z_beta: [8, -0.025, -3., 3., 0.1, 'n_e']
    #gamma_B16: -0.2
    #xc_B16: 0.5

    # power-law break (density)
#    alphap_m_rho0: [9, 0.29, -3., 3., 0.1, 'n_e']
#    alphap_m_alpha: [10, -0.03, -3., 3., 0.1, 'n_e']
#    alphap_m_beta: [11, 0.04, -3., 3., 0.1, 'n_e']
#    Mcut_break: [12, 13.8, 12.5, 14.5, 0.05, 'n_e']

    # concentration dependence (density)
#    alpha_c_rho0: [13, 0., -3., 3., 0.1, 'n_e']
#    alpha_c_alpha: [14, 0., -3., 3., 0.1, 'n_e']
#    alpha_c_beta: [15, 0., -3., 3., 0.1, 'n_e']
    
    # two-halo fudge factor (density)
#    A_A2h: [13, 1., 0.5, 10., 0.1, 'n_e']
#    alpha_z_A2h: [14, 0., -3., 3., 0.1, 'n_e']
#    alpha_m_A2h: [15, 0., -3., 3., 0.1, 'n_e']
#    alpha_c_A2h: [19, 0., -3., 3., 0.1, 'n_e']

# Configuration parameters for emcee
ch_config_params:
    path2output: /global/cscratch1/sd/boryanah/SZ_TNG/chains/mtng
    chainsPrefix: mtng_P_e_power
    use_mpi: 0
    rerun: 0
    walkersRatio: 4
    burninIterations: 2000
    sampleIterations: 120000